version: '3'
services:
  db:
    image: postgres:11
    environment:
      - "POSTGRES_PASSWORD=postgres"
    ports:
    - 5432:5432
  server:
    build:
      context: .
    restart: on-failure
    environment:
      - "DATABASE_HOST=db"
    ports:
    - 8000:80
    depends_on:
      - db